language: php

php:
  - 7.3
  - 7.4
  - 8.0

sudo: false

matrix:
  fast_finish: true

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --format=txt --verbose --diff --diff-format=udiff --allow-risky=yes --config=.php_cs.dist
  - vendor/bin/phpstan analyse src tests -l max

before_script:
  - composer install
